//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScreenAnnotation.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScreenAnnotation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Saved to {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_CaptureComplete {
            get {
                return ResourceManager.GetString("Msg_CaptureComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error capturing screen: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_CaptureError {
            get {
                return ResourceManager.GetString("Msg_CaptureError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   全ての注釈をクリアしてもよろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_ClearConfirm {
            get {
                return ResourceManager.GetString("Msg_ClearConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   終了してもよろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_ExitConfirm {
            get {
                return ResourceManager.GetString("Msg_ExitConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error loading file: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_LoadError {
            get {
                return ResourceManager.GetString("Msg_LoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルの読み込みに失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_LoadParseError {
            get {
                return ResourceManager.GetString("Msg_LoadParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保存する注釈がありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_NoAnnotationsToSave {
            get {
                return ResourceManager.GetString("Msg_NoAnnotationsToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Saved to {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_SaveComplete {
            get {
                return ResourceManager.GetString("Msg_SaveComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error saving file: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_SaveError {
            get {
                return ResourceManager.GetString("Msg_SaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャンセル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Settings_Cancel {
            get {
                return ResourceManager.GetString("Settings_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保存 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Settings_Save {
            get {
                return ResourceManager.GetString("Settings_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再開時刻を表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Settings_ShowResumeTime {
            get {
                return ResourceManager.GetString("Settings_ShowResumeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スリープ画面表示文 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Settings_SleepTextLabel {
            get {
                return ResourceManager.GetString("Settings_SleepTextLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ツールバーのスケール に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Settings_ToolbarScaleLabel {
            get {
                return ResourceManager.GetString("Settings_ToolbarScaleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャンセル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Status_Cancel {
            get {
                return ResourceManager.GetString("Status_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   現在時刻 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Status_CurrentTime {
            get {
                return ResourceManager.GetString("Status_CurrentTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再開時刻 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Status_ResumeTime {
            get {
                return ResourceManager.GetString("Status_ResumeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   時刻 (HH:mm): に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Status_ResumeTimeDialogLabel {
            get {
                return ResourceManager.GetString("Status_ResumeTimeDialogLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再開時間を設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Status_ResumeTimeDialogTitle {
            get {
                return ResourceManager.GetString("Status_ResumeTimeDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ScreenAnnotation - キャプチャ保存完了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Title_CaptureComplete {
            get {
                return ResourceManager.GetString("Title_CaptureComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ScreenAnnotation - クリア確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Title_ClearConfirm {
            get {
                return ResourceManager.GetString("Title_ClearConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ScreenAnnotation - エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Title_Error {
            get {
                return ResourceManager.GetString("Title_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ScreenAnnotation - 終了確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Title_ExitConfirm {
            get {
                return ResourceManager.GetString("Title_ExitConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ScreenAnnotation - 情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Title_Info {
            get {
                return ResourceManager.GetString("Title_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ScreenAnnotation - 保存完了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Title_SaveComplete {
            get {
                return ResourceManager.GetString("Title_SaveComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   矢印を追加 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Tooltip_AddArrow {
            get {
                return ResourceManager.GetString("Tooltip_AddArrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   吹き出しを追加 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Tooltip_AddText {
            get {
                return ResourceManager.GetString("Tooltip_AddText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   画面キャプチャ（PNG保存） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Tooltip_Capture {
            get {
                return ResourceManager.GetString("Tooltip_Capture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   全消去 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Tooltip_Clear {
            get {
                return ResourceManager.GetString("Tooltip_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   終了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Tooltip_Exit {
            get {
                return ResourceManager.GetString("Tooltip_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バージョン情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Tooltip_Information {
            get {
                return ResourceManager.GetString("Tooltip_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   読み込み（JSON） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Tooltip_Load {
            get {
                return ResourceManager.GetString("Tooltip_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ディスプレイを切り替え に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Tooltip_NextDisplay {
            get {
                return ResourceManager.GetString("Tooltip_NextDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保存（JSON） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Tooltip_Save {
            get {
                return ResourceManager.GetString("Tooltip_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スリープ表示テキスト設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Tooltip_Settings {
            get {
                return ResourceManager.GetString("Tooltip_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   休憩・離席 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Tooltip_Sleep {
            get {
                return ResourceManager.GetString("Tooltip_Sleep", resourceCulture);
            }
        }
    }
}
